/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.interfaces;
import com.formdev.flatlaf.FlatDarkLaf;
/**
 *
 * @author Ryzen 5
 */
public class CrearRegistro extends javax.swing.JFrame {

    /**
     * Creates new form Registros
     */
    public CrearRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlCTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlCCenter = new javax.swing.JPanel();
        lblNombreItinerario = new javax.swing.JLabel();
        txtfNombreItinerario = new javax.swing.JTextField();
        lblDias = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        lblMap = new javax.swing.JLabel();
        pnlCBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setBackground(new java.awt.Color(0, 23, 31));
        pnlSide.setPreferredSize(new java.awt.Dimension(100, 648));

        jPanel1.setBackground(new java.awt.Color(0, 23, 31));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jButton1.setBackground(new java.awt.Color(0, 23, 31));
        jButton1.setForeground(new java.awt.Color(0, 23, 31));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/icons8_back_to_60px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        pnlSide.add(jPanel1);

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(0, 52, 81));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlCTop.setBackground(new java.awt.Color(0, 52, 81));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Registro de nuevo itinerario");

        javax.swing.GroupLayout pnlCTopLayout = new javax.swing.GroupLayout(pnlCTop);
        pnlCTop.setLayout(pnlCTopLayout);
        pnlCTopLayout.setHorizontalGroup(
            pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCTopLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(716, Short.MAX_VALUE))
        );
        pnlCTopLayout.setVerticalGroup(
            pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCTopLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnlCenter.add(pnlCTop, java.awt.BorderLayout.PAGE_START);

        pnlCCenter.setBackground(new java.awt.Color(0, 52, 81));
        pnlCCenter.setForeground(new java.awt.Color(0, 185, 249));
        pnlCCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreItinerario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreItinerario.setText("Nombre del Itinerario:");
        pnlCCenter.add(lblNombreItinerario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        txtfNombreItinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNombreItinerarioActionPerformed(evt);
            }
        });
        pnlCCenter.add(txtfNombreItinerario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 280, -1));

        lblDias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDias.setText("Dias:");
        pnlCCenter.add(lblDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        jCheckBox1.setText("L");
        pnlCCenter.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, -1));

        jCheckBox2.setText("D");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        pnlCCenter.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, -1, -1));

        jCheckBox3.setText("Ma");
        pnlCCenter.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, -1));

        jCheckBox4.setText("Mi");
        pnlCCenter.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, -1, -1));

        jCheckBox5.setText("J");
        pnlCCenter.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, -1, -1));

        jCheckBox6.setText("V");
        pnlCCenter.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 60, -1, 20));

        jCheckBox7.setText("S");
        pnlCCenter.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, -1, -1));

        jLabel3.setText("Hora");
        pnlCCenter.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 30, -1));

        jLabel4.setText("de");
        pnlCCenter.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 120, 30, -1));

        jLabel5.setText("Inicio");
        pnlCCenter.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        jLabel6.setText(":");
        pnlCCenter.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        jFormattedTextField2.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlCCenter.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 40, -1));

        jFormattedTextField5.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlCCenter.add(jFormattedTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 40, -1));

        jFormattedTextField6.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlCCenter.add(jFormattedTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 40, -1));

        jFormattedTextField7.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlCCenter.add(jFormattedTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 40, -1));

        jFormattedTextField8.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlCCenter.add(jFormattedTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 40, -1));

        jFormattedTextField9.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlCCenter.add(jFormattedTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 40, -1));

        jFormattedTextField10.setPreferredSize(new java.awt.Dimension(60, 22));
        pnlCCenter.add(jFormattedTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 120, 40, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Longitud del recorrido");
        pnlCCenter.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Max. participantes");
        pnlCCenter.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/icons8_sneaker_40px_1.png"))); // NOI18N
        pnlCCenter.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 250, 40, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("130");
        pnlCCenter.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, -1, -1));

        jLabel11.setText("Metros");
        pnlCCenter.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 235, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("20");
        pnlCCenter.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, -1, -1));

        jLabel13.setText("Minutos");
        pnlCCenter.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 235, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/icons8_User_Groups_40px.png"))); // NOI18N
        pnlCCenter.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, 40, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Duracion del recorrido");
        pnlCCenter.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("60");
        pnlCCenter.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/icons8_clock_40px.png"))); // NOI18N
        pnlCCenter.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 40, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tipo de recorrido");
        pnlCCenter.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        jToggleButton2.setBackground(new java.awt.Color(0, 126, 167));
        jToggleButton2.setText("Por zonas");
        jToggleButton2.setPreferredSize(new java.awt.Dimension(93, 30));
        pnlCCenter.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        jToggleButton1.setBackground(new java.awt.Color(0, 126, 167));
        jToggleButton1.setText("Por habitats");
        jToggleButton1.setPreferredSize(new java.awt.Dimension(93, 30));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        pnlCCenter.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 52, 81));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 185, 249));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/icons8_checked_checkbox_80px_1.png"))); // NOI18N
        jButton2.setText("SAVE");
        jButton2.setBorder(null);
        pnlCCenter.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, -1, -1));

        jToggleButton3.setBackground(new java.awt.Color(62, 170, 206));
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/icons8_b_50px.png"))); // NOI18N
        jToggleButton3.setBorder(null);
        pnlCCenter.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jToggleButton4.setBackground(new java.awt.Color(62, 170, 206));
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/icons8_c_50px.png"))); // NOI18N
        jToggleButton4.setBorder(null);
        pnlCCenter.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jToggleButton5.setBackground(new java.awt.Color(62, 170, 206));
        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/icons8_d_50px.png"))); // NOI18N
        jToggleButton5.setBorder(null);
        pnlCCenter.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jToggleButton6.setBackground(new java.awt.Color(62, 170, 206));
        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/icons8_e_50px.png"))); // NOI18N
        jToggleButton6.setBorder(null);
        pnlCCenter.add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jToggleButton7.setBackground(new java.awt.Color(62, 170, 206));
        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/icons8_a_50px_1.png"))); // NOI18N
        jToggleButton7.setBorder(null);
        pnlCCenter.add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        lblMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itson/imagenes/zoomap-zonas.png"))); // NOI18N
        lblMap.setText("jLabel3");
        pnlCCenter.add(lblMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 660, 420));

        pnlCenter.add(pnlCCenter, java.awt.BorderLayout.CENTER);

        pnlCBottom.setBackground(new java.awt.Color(0, 52, 81));
        pnlCBottom.setPreferredSize(new java.awt.Dimension(1147, 50));

        javax.swing.GroupLayout pnlCBottomLayout = new javax.swing.GroupLayout(pnlCBottom);
        pnlCBottom.setLayout(pnlCBottomLayout);
        pnlCBottomLayout.setHorizontalGroup(
            pnlCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        pnlCBottomLayout.setVerticalGroup(
            pnlCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCBottom, java.awt.BorderLayout.SOUTH);

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txtfNombreItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNombreItinerarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNombreItinerarioActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatDarkLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblMap;
    private javax.swing.JLabel lblNombreItinerario;
    private javax.swing.JPanel pnlCBottom;
    private javax.swing.JPanel pnlCCenter;
    private javax.swing.JPanel pnlCTop;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JTextField txtfNombreItinerario;
    // End of variables declaration//GEN-END:variables
}
